name: Update Website

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Update timestamp
      run: |
        sed -i "s/Last updated:.*/Last updated: $(date)/" index.html
        
    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git add index.html
        git commit -m "Auto update: $(date)" || exit 0
        git push
